# Pytorch Fundamentals

### What is PyTorch?

PyTorch is an open source machine learning and deep learning framework.

Reference: 

- [Pytorch Tutorial Github](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb)
- [Discussion Page](https://github.com/mrdbourke/pytorch-deep-learning/discussions)
- [Pytorch Developer Forum](https://discuss.pytorch.org/)


> Note: Before running any of the code in this notebook, you should have gone through the [PyTorch setup steps](https://pytorch.org/get-started/locally/).
> 
> However, if you're running on Google Colab, everything should work (Google Colab comes with PyTorch and other libraries installed).

In [2]:
!python --version

Python 3.12.1


In [4]:
# importing pytorch

import torch
torch.__version__

'2.9.1+cpu'

![tensors](https://camo.githubusercontent.com/89805c11e270c9a9f9c22fca9f0c0d990e87a007f02b292db8ee2474374eb52f/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d7264626f75726b652f7079746f7263682d646565702d6c6561726e696e672f6d61696e2f696d616765732f30302d74656e736f722d73686170652d6578616d706c652d6f662d696d6167652e706e67)

Here, you could represent an image as a tensor with shape `[3, 224, 224`] which would mean `[colour_channels, height, width]`, as in the image has `3` colour channels (red, green, blue), a height of `224` pixels and a width of `224` pixels.

In [5]:
# creating scalar using tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
print(scalar.ndim)
print(scalar.item()) #only works with one-element tensors
print(scalar.shape)

0
7
torch.Size([])


In [7]:
# vector
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [12]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


In [13]:
# Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


![scalar-tensor](https://camo.githubusercontent.com/2750a4235d2e1bd63915f8fb02e78f3d0796722ac16bc5e65eef34240019515c/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d7264626f75726b652f7079746f7263682d646565702d6c6561726e696e672f6d61696e2f696d616765732f30302d7363616c61722d766563746f722d6d61747269782d74656e736f722e706e67)

In [19]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.3793, 0.9537, 0.8257],
         [0.2394, 0.4827, 0.8397]]),
 torch.float32)

In [20]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [23]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6960, 0.3192, 0.6461, 0.8018],
        [0.5592, 0.8016, 0.1047, 0.3079],
        [0.1570, 0.8485, 0.3892, 0.5884]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor Operations

In [29]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [31]:
tensor

tensor([1, 2, 3])

In [32]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [33]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the `torch.matmul()` method.

Note: 
- Inner dimensions should match
- Resulting matrix has the shape of the outer dimensions

For example: `(2, 3)` @ `(3, 2)` -> `(2, 2)`

In [36]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


Squeeze and Unsqueeze funtions. 

In [ ]:
# Standalone example: why unsqueeze -> make (N,) into (N, 1) for (batch, features)
import torch
from torch import nn

t = torch.tensor([0., 1., 2., 3., 4.], dtype=torch.float32)
print("t shape:", t.shape)               # (5,)

t_unsq = t.unsqueeze(1)                  # add a feature dimension
print("t.unsqueeze(1) shape:", t_unsq.shape)  # (5, 1)

t_resh = t.reshape(-1, 1)                # alternative
print("t.reshape(-1,1) shape:", t_resh.shape)

# nn.Linear expects input shape (batch_size, in_features)
linear = nn.Linear(in_features=1, out_features=2)
out = linear(t_unsq)                     # works: (5,1) -> (5,2)
print("linear output shape:", out.shape)

# Passing 1D tensor to nn.Linear raises an error
try:
    linear(t)
except Exception as e:
    print("Error when passing 1D tensor to nn.Linear:", e)